name: sublime-text
version: '3143'
summary: A sophisticated text editor for code, markup and prose.
description: |
  A sophisticated text editor for code, markup and prose.

grade: stable
confinement: classic
architectures:
  - amd64

apps:
  subl:
    command: sublime_text
    desktop: sublime_text.desktop

parts:
  sublime-text:
    plugin: dump
    source: https://download.sublimetext.com/sublime_text_3_build_$SNAPCRAFT_PROJECT_VERSION_x64.tar.bz2
    install: |
      sed -i 's|Icon=.*|Icon=/Icon/256x256/sublime-text.png|g' $SNAPCRAFT_PART_INSTALL/sublime_text.desktop
      sed -i 's|/opt/sublime_text/sublime_text|'"$SNAP"'/sublime_text|g' $SNAPCRAFT_PART_INSTALL/sublime_text.desktop
    stage-packages:
      - libgtk2.0-0
      - libc6
