name: sublime-text-3
version: '3143'
version-script: |
  curl https://download.sublimetext.com/latest/stable
summary: A sophisticated text editor for code, markup and prose.
description: |
  A sophisticated text editor for code, markup and prose.

grade: stable
confinement: classic
architectures:
  - amd64

apps:
  sublime-text-3:
    command: sublime_text
    desktop: sublime_text.desktop

parts:
  android-studio:
    plugin: dump
    source: https://download.sublimetext.com/sublime_text_3_build_$SNAPCRAFT_PROJECT_VERSION_x64.tar.bz2
